#NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")

# Trigger CD when CI executed succesfully
resources:
  pipelines:
    - pipeline: AplicativoWeb
      source: AplicativoWeb # given pipeline name
      trigger: true


variables:
  resource-group: 'AZ400-EWebShop-NAME'
  location: 'eastus'
  templateFile: '.azure/bicep/webapp.bicep'
  subscriptionid: '7f62f0c4-db44-4d69-9eb0-c8f6f50718d9'
  azureserviceconnection: 'terraformteste'
  webappname: 'az400-webapp-teste23'
  # webappname: 'webapp-windows-eshop'
  

stages:
- stage: Deploy
  displayName: Deploy to WebApp
  jobs:
  - job: Deploy
    pool:
      vmImage: windows-latest
    steps:
    #download artifacts
    - download: AplicativoWeb
  
    # Deploy App Service Plan + App Service using Bicep
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy App Service Plan Bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureserviceconnection)'
        subscriptionId: '$(subscriptionid)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resource-group)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(templateFile)'
        overrideParameters: '-webAppName $(webappname) -location $(location)'
        deploymentMode: 'Incremental'
        deploymentOutputs: 'asp-json'
    
    #Publish Website to Azure WebApp
    - task: AzureRmWebAppDeployment@4
      displayName: Publish Website to WebApp
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'terraformteste'
        appType: 'webApp'
        WebAppName: '$(webappname)'
        packageForLinux: '$(Pipeline.Workspace)/**/Web.zip'
      

    
